# Prometheus configuration for Universal Payment Protocol
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules configuration
rule_files:
  # - "alert_rules.yml"

# Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# The individual scrape configs in this file are only for demonstration purposes.
# Replace them with your own scrape configs.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'upp-server'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:3000']
        labels:
          service: 'upp-server'
          environment: 'development'

  - job_name: 'upp-stripe-integration'
    static_configs:
      - targets: ['localhost:3000']
        labels:
          service: 'stripe-integration'
          environment: 'development'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          service: 'node-exporter'
          environment: 'development'

# Global DNS configuration.
# dns_sd_configs:
#   - names:
#       - 'prometheus-dns-sd.example.org'
#     type: 'A'
#     port: 9090

# File-based service discovery.
# file_sd_configs:
#   - files:
#       - 'targets.json'

# HTTP-based service discovery.
# http_sd_configs:
#   - url: 'http://discovery.example.com/prometheus'

# Consul-based service discovery.
# consul_sd_configs:
#   - server: 'consul.example.com:8500'
#     services: ['upp-server']

# Kubernetes-based service discovery.
# kubernetes_sd_configs:
#   - role: 'pod'
#     namespaces:
#       names:
#         - 'upp-namespace'
