name: Check that GitHub Pages Builds

permissions: {}

on:
  push:
jobs:
  build:
    name: Build Docusaurus
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: 'docusaurus/package-lock.json'
      - name: Install dependencies
        run: cd docusaurus && npm ci
      - name: Build website
        run: cd docusaurus && npm run build
