apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    jsonData:
      httpMethod: GET
      timeInterval: "5s"
    editable: true

  - name: UPP-Alerts
    type: alertmanager
    access: proxy
    url: http://localhost:9093
    jsonData:
      implementation: "prometheus"
    editable: true
